### ISSUE TITLE
Try to enable plugin via `'plugin:vue-pug/vue3-recommended'`

### ISSUE THREAD

**Issue by Shinigami92** [rashfael/eslint-plugin-vue-pug#1]
My config:

```js
// @ts-check
const { defineConfig } = require('eslint-define-config');
const { readGitignoreFiles } = require('eslint-gitignore');

module.exports = defineConfig({
  ignorePatterns: [...readGitignoreFiles(), '.eslintrc.js'],
  root: true,
  env: {
    node: true,
    jest: true,
  },
  extends: [
    'plugin:@typescript-eslint/recommended',
    'plugin:vue/vue3-recommended',
    'plugin:vue-pug/vue3-recommended', // <=========== That is the important row!
    'plugin:prettier/recommended',
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: 'tsconfig.lint.json',
    sourceType: 'module',
    warnOnUnsupportedTypeScriptVersion: false,
  },
  plugins: ['@typescript-eslint/eslint-plugin'],
  rules: {
    '@typescript-eslint/consistent-type-imports': 'error',
    '@typescript-eslint/explicit-function-return-type': [
      'error',
      { allowExpressions: true },
    ],
    '@typescript-eslint/interface-name-prefix': 'off',
    '@typescript-eslint/lines-between-class-members': [
      'warn',
      'always',
      { exceptAfterSingleLine: true },
    ],
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-unused-vars': 'off',
  },
  overrides: [
    {
      files: ['*.vue'],
      parser: 'vue-eslint-parser',
      parserOptions: {
        parser: '@typescript-eslint/parser',
        project: 'tsconfig.json',
        extraFileExtensions: ['.vue'],
        templateTokenizer: {
          pug: 'vue-eslint-parser-template-tokenizer-pug', // <==== Configured for .vue
        },
        tsconfigRootDir: './',
      },
    },
  ],
});
```

Getting following error:

```node
> pnpm run lint

> vfid-frontend@1.0.0-alpha.1 lint /Users/shinigami/Dermalog/frontend
> eslint --ext .ts,.vue src


Oops! Something went wrong! :(

ESLint: 8.12.0

ESLint couldn't find the plugin "eslint-plugin-vue-pug".

(The package "eslint-plugin-vue-pug" was not found when loaded as a Node module from the directory "/Users/shinigami/Dermalog/frontend".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-vue-pug@latest --save-dev

The plugin "eslint-plugin-vue-pug" was referenced from the config file in ".eslintrc.js".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

 ELIFECYCLE  Command failed with exit code 2.
```

I doubled ensure that it is installed

![image](https://user-images.githubusercontent.com/7195563/160849286-edf0c5c2-31ae-4c9c-97de-e2681fe8a44f.png)

How do I activate the rules for pug?

**Comment by Shinigami92** [comment]
> I never actually published a running version, since it's a bit of a pain to setup currently. I released a version that works (and a new `vue-eslint-parser-template-tokenizer-pug` version), but you will need clone [https://github.com/rashfael/vue-eslint-parser/tree/custom-template-tokenizers](https://github.com/rashfael/vue-eslint-parser/tree/custom-template-tokenizers?rgh-link-date=2022-03-30T13%3A58%3A08Z) and `npm link` that into your actual project.

Due to I'm using this in a closed company software, I'm not able to do that, so I need to wait on the finished working version

**Comment by ota-meshi** [comment]
I have released an alpha version of vue-eslint-parser.

https://github.com/vuejs/vue-eslint-parser/releases/tag/v9.0.0-alpha.0

**Comment by rashfael** [comment]
Version 0.3.0 of eslint-plugin-vue-pug uses the new vue-eslint-parser. Since eslint-plugin-vue still has v8 in its dependencies, you have to install vue-eslint-parser@next manually. Something like this works for my projects:
```
 npm install -D eslint@8 eslint-plugin-vue eslint-plugin-vue-pug vue-eslint-parser@next vue-eslint-parser-template-tokenizer-pug
```

I'm currently fixing a bug in the tokenizer I found when I ran the linter on one of my bigger projects and then I will write a Getting Started guide.

**Comment by Shinigami92** [comment]
I may try it on tuesday at work

**Comment by Shinigami92** [comment]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/7195563/164029452-b1a1cb1a-5b32-408e-b41e-6bb75b0fb3f9.png">

**Comment by rashfael** [comment]
I still have issues with getting one of my projects to lint, which is why I am rewriting the tokenizer currently (pug-parser does not report the ranges for the end of a tag's content so we can't generate correct "virtual" end tags).
Awesome that it works for you :)

**Comment by rashfael** [comment]
I have rewritten the parser in v0.4 to output more accurate tokens and it's working for my biggest project now.
