### ISSUE TITLE
eslint-plugin-vue v10 support

### ISSUE THREAD

**Issue by EvgeniyaSbitneva** [rashfael/eslint-plugin-vue-pug#32]
Do you have any plans to upgrade your plugin to be compatible with the new eslint-plugin-vue?

**Comment by rashfael** [comment]
I just released a new version that is compatible with eslint-plugin-vue@10

https://github.com/rashfael/eslint-plugin-vue-pug/issues/29#issuecomment-2746127572

**Comment by NGPixel** [comment]
@waltiam Read the link comment he posted? You need to use `eslint-plugin-vue-pug@flat`

**Comment by tbontb-iaq** [comment]
pnpm warns me that  `Issues with peer dependencies found`:

```
pnpm i -D eslint-plugin-vue-pug                     
Already up to date
Progress: resolved 583, reused 522, downloaded 0, added 0, done
 WARN  Issues with peer dependencies found
.
├─┬ eslint-plugin-vue 10.0.0
│ └── ✕ missing peer vue-eslint-parser@^10.0.0
└─┬ eslint-plugin-vue-pug 0.6.2
  ├── ✕ unmet peer eslint-plugin-vue@^9.8.0: found 10.0.0
  └─┬ vue-eslint-parser-template-tokenizer-pug 0.4.11
    └── ✕ missing peer vue-eslint-parser@^9.0.0
✕ Conflicting peer dependencies:
  vue-eslint-parser
Done in 14.5s using pnpm v10.6.5
```

**Comment by richardsimko** [comment]
@rashfael Any chance the peer dependency on `eslint-plugin-vue` can be changed to `^10.0.0` instead of `10.0.0`? They just released 10.1.0 which can't be installed together with `eslint-plugin-vue-pug@1.0.0-alpha.2`

**Comment by lehni** [comment]
@rashfael could you please consider merging #30? I am still facing the same issue with v1.0.0-alpha.2 and eslint v9.
Merging #30 would fix that.

Also, I cannot find the flat branch that was released as v1.0.0. Is it not on Github?

**Comment by rashfael** [comment]
ah, good catch, @richardsimko ! I'll publish a fix.

**Comment by rashfael** [comment]
@lehni I did indeed forget to push. Please don't comment on unrelated issues though.
